name: build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build

