name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./
      - run: |
          npm publish

